version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.4.2-jessie-node
      environment:
        PGHOST: 127.0.0.1
        PGUSER: $RAILS_PG_USER
        RAILS_ENV: test
    - image: circleci/postgres:9.5-alpine
      environment:
        POSTGRES_USER: circleci-demo-ruby
        POSTGRES_DB: rails_blog
        POSTGRES_PASSWORD: ""
    steps:
    - checkout
    - run:
        name: Bundle install
        command: bundle install --path vendor/bundle
    - run:
        name: Wait for DB
        command: dockerize -wait tcp://localhost:5432 -timeout 1m
    - run:
        name: Database setup
        command: bin/rails db:schema:load --trace
    - run:
        name: Run rspec in parallel
        command: |
          bundle exec rspec

  lint:
    docker:
    - image: circleci/ruby:2.4.2-jessie-node
    steps:
    - checkout
    - run:
        name: Bundle install
        command: bundle install --path vendor/bundle
    - run:
        name: Run lint
        command: |
          bundle exec rails_best_practices

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: demo
      - lint
